### ISSUE TITLE
Inference code?

### ISSUE THREAD

**Issue by ghost** [yuhangzang/OV-DETR#10]
Hi, this is really an excellent idea.
Could you provide the demo code or inference code to see the outcome of the model?

Best,
Tin

**Comment by Davidyao99** [comment]
Hi, did you manage to find / create the demo or inference code? I am also interested! Thanks!

**Comment by Kris-Lcq** [comment]
> Hi, did you manage to find / create the demo or inference code? I am also interested! Thanks!

Same question
