### ISSUE TITLE
The AP results on COCO?

### ISSUE THREAD

**Issue by ghost** [yuhangzang/OV-DETR#12]
Hi,
I am Tin, a student who found this work very interesting.
However, when I run the evaluation like this:
`GPU_VISIBLE_DEVICES=0,1,3,4,5,6,7 python -m torch.distributed.launch     --nproc_per_node=1     --use_env main.py     --dataset_file coco     --coco_path ../../Detic/Detic/datasets/coco/     --output_dir ./output/     --num_queries 100     --with_box_refine     --two_stage     --label_map     --eval     --resume ../coco_model.pth \`

<img width="650" alt="Screen Shot 2022-10-06 at 4 02 17 PM" src="https://user-images.githubusercontent.com/17596799/194425868-92df52bf-b0af-41b7-bd06-7a803d58c185.png">

The results are even better than your reported results on the paper, concretely, this is your table 4.
<img width="911" alt="Screen Shot 2022-10-06 at 4 55 23 PM" src="https://user-images.githubusercontent.com/17596799/194425930-ab8756fc-144a-4726-b478-55cd3c4be599.png">

I am perplexed now and I really need to understand how come it is to make sure that I am doing right and move to further steps.

Hope that you will clarify it. Thank you very much for your contribution.

Best,
Tin

**Comment by youqingxiaozhua** [comment]
My results are about 42 for seen and 20 for seen. Could you please share your findings?
