### ISSUE TITLE
Can not reproduce the reported performance on COCO 

### ISSUE THREAD

**Issue by youqingxiaozhua** [yuhangzang/OV-DETR#17]
Thanks for your great and inspiring work on open-vocabulary detection.

But after directly running the released codes, I only get about 20 AP50 for unseen and 42 for seen, which is under a big gap with reported (29.4, 61.0). Is there any operation that has not been included in current released codes?

Thanks.

**Comment by youqingxiaozhua** [comment]
I have solved the problem, sorry for bothering.

**Comment by stlmx** [comment]
Could you please teache me how to solve? I have met the same problem as yours.
Thanks a lot !
